# Generated by Django 2.2.16 on 2021-09-05 15:56

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0009_auto_20210905_1319'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, help_text='Дата публикации комента', verbose_name='Дата создания комента'),
            preserve_default=False,
        ),
    ]
